name: GitHub Profile Views Counter CI
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}
      - uses: actions/setup-node@v1.0.0
        with:
          node-version: 14.17.0
      - uses: Mohamed3nan/Views-Action@v3.3.0
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
